### ISSUE TITLE
Public folder issue!

### ISSUE THREAD

**Issue by Tekhlay** [MohamedHNoor/space-travelers#30]
Hi @teams
Congratulations! on your project accomplishment! 💪 

##### To Highlights

- [x] All Linter checks are passsing✔️ 
- [x] Goode code base✔️ 
- [x] Meaningful commit messages✔️ 
- [x] Professional readme file ✔️ 
- [x] Professional workflow structure✔️ 
- [x] App works well and sticks with the given design ✔️ 

##### As Optional ♻️ 

Kindly edit the public folder on your project since it is part of the contribution, it seems simple but it needs commitment and attention. change the default logos and project title to your own they are helpful for SEO purposes.

**Comment by MohamedHNoor** [comment]
Hi @Tekhlay, Thank you for the suggestions I will apply them

**Comment by MohamedHNoor** [comment]
The public folder has been updated
